### ISSUE TITLE
Error when trying to build on Ubuntu

### ISSUE THREAD

**Issue by micnic** [waleedahmad/Snipper#1]
When trying to build the executables for Ubuntu using `npm run dist` it throws the following error:

> Error: Please specify author 'email' in the application package.json
>
> See https://docs.npmjs.com/files/package.json#people-fields-author-contributors
>
> It is required to set Linux .deb package maintainer. Or you can set maintainer in the custom linux options.
(see https://www.electron.build/configuration/linux).

Please provide the `email` field in the `author` section of `package.json`

**Comment by waleedahmad** [comment]
Fixed in cdb9d8d2348f4ae53a8ae2e6af547617b1de49de
